const images = {
  tabHome: require("../../src/assets/images/tab_icons/home_icon.png"),
  tabHomeSelect: require("../../src/assets/images/tab_icons/home_select.png"),
  tabCart: require("../../src/assets/images/tab_icons/cart_icon.png"),
  tabCartSelect: require("../../src/assets/images/tab_icons/cart_select.png"),
  tabInfo: require("../../src/assets/images/tab_icons/missing.png"),
  tabInfoSelect: require("../../src/assets/images/tab_icons/missing_selected.png"),
  tabCreated: require("../../src/assets/images/tab_icons/created_icon.png"),
  tabCreatedSelect: require("../../src/assets/images/tab_icons/created_select.png"),
  tabCreateNew: require("../../src/assets/images/tab_icons/create_id.png"),
  tabCreateNewUnselected: require("../../src/assets/images/tab_icons/create_id_unselected.png"),

  kidsIDTemplate: require("../../src/assets/images/kidsid.png"),
  kidPhotoTemplate: require("../../src/assets/images/baby5-fix.png"),
  logiTemplate: require("../../src/assets/images/freekidslogo.png"),
  blankPhoto: require("../../src/assets/images/blank.png"),
  messageIcon: require("../../src/assets/images/header-message.png"),
  headerCheckIcon: require("../../src/assets/images/header-check.png"),
  cardTopSlot: require("../../src/assets/images/cardtop-slot.png"),
  buttonGradient: require("../../src/assets/images/button-gradient.png"),

  phoneIcon: require("../../src/assets/images/phone.png"),
  phoneIcon1: require("../../src/assets/images/phone1.png"),
  birthdayIcon: require("../../src/assets/images/birthday.png"),
  medicalIcon: require("../../src/assets/images/medical.png"),
  noteIcon: require("../../src/assets/images/notes.png"),
  blankBaby: require("../../src/assets/images/blankbaby.jpg"),
  babyId: require("../../src/assets/images/babyid.png"),
};
export default images;
